Series

In [ ]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

obj = pd.Series([1,-3,5,1,4])
print(obj)

print(obj.array)
print(obj.index)

obj1 = pd.Series([1,2,3,4], index=["a","b","c","d"])
print(obj1)

print(obj1["a"])
obj1["d"] = -20
print(obj1)

print(obj[obj > 0])

print(obj1 * 2)

print(np.exp(obj1))

print("b" in obj1)
print("e" in obj1) 

sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

obj2 = pd.Series(sdata)
print(obj2)
print(obj2.to_dict)

states = ["California", "Ohio", "Oregon", "Texas"]
obj3 = pd.Series(sdata, index=states)
print(obj3)

print(pd.notna(obj3))
print(pd.isna(obj3))

print(obj1+obj2)

obj2.name = 'Population'
obj2.index.name = 'State'
obj2 #this is the method to print in jupyter

DataFrame

In [40]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
 "year": [2000, 2001, 2002, 2001, 2002, 2003],
 "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame
frame.head() #will print first 5 rows
frame.tail() #will print last 5 rows

frame2 = pd.DataFrame(data,columns=["year","state","pop"])
frame2

frame2 = pd.DataFrame(data,columns=["year","state","pop","debt"])
print(frame2)
frame2.columns
frame2["state"] 
frame2.year
frame2["Price"] = None
frame2
print(frame2.loc[0,"pop"])
print("\n")
print(frame2.iloc[2,0])

frame2["debt"] = np.arange(6.)
frame2["Price"] = np.arange(6.)
frame2

frame2["debt"] = 1000
frame2

frame2["eastern"] = frame2["state"] == "Ohio"
frame2

del frame2["eastern"]
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN
1.5


2002

   year   state  pop  debt  Price
0  2000    Ohio  1.5  1000    0.0
1  2001    Ohio  1.7  1000    1.0
2  2002    Ohio  3.6  1000    2.0
3  2001  Nevada  2.4  1000    3.0
4  2002  Nevada  2.9  1000    4.0
5  2003  Nevada  3.2  1000    5.0

Indexes

In [83]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

obj = pd.Series(np.arange(3),index=["a","b","c"])
obj

index = obj.index
index
index[1:]

# index[1] = "d"  IMMUTABILITY
labels = pd.Index(np.arange(3))
print(labels)

obj2 = pd.Series([1.5,-2.5,0],index=labels)
obj2

obj2.index is labels

Index([0, 1, 2], dtype='int64')

True

Reindexing

In [84]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

print(obj3.reindex(np.arange(6),method="ffill"))

frame = pd.DataFrame(np.arange(9).reshape(3,3),index=["a","c","d"],columns=["Ohio","Texas","California"])
frame

frame.loc[["a","d","c"], ["California","Texas","Ohio"]]

data = pd.DataFrame(np.arange(16).reshape((4, 4)),
        index=["Ohio", "Colorado", "Utah", "New York"],
        columns=["one", "two", "three", "four"])
data

data < 5

data[data < 5] = 0
data

data.loc[:"Utah","two"]
data
data.iloc[:,:3][data.three > 5]

data.at["Utah","one"]

data.loc["Ohio":"Utah","one"] = 1
data

data.iloc[2,3] = 1
data

data.loc[data["three"] > 8] = 13
data

data.loc["Ohio",:] = 5

data.loc["Utah"] = 2
print(data)

data.loc[data.two == 5,"two"] = 32
data

#170 se continue
data

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str
          one  two  three  four
Ohio        5    5      5     5
Colorado    1    5      6     7
Utah        2    2      2     2
New York   13   13     13    13

          one  two  three  four
Ohio        5   32      5     5
Colorado    1   32      6     7
Utah        2    2      2     2
New York   13   13     13    13

Operations on DataFrame and Series

In [113]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame


df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))

df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                   columns=list("abcde"))

df1 + df2

df1.add(df2,fill_value=0)

1/df1

df1.rdiv(3)

print(df1.reindex(columns=df2.columns,fill_value=0))
dframe = pd.DataFrame(np.arange(12.).reshape(4,3),index=[0,1,2,3],columns=list("bde"))
print(dframe)

series = dframe.iloc[0]
series

dframe - series

series2 = dframe["d"]

series2

dframe.sub(series2,axis="index")

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0
     b     d     e
0  0.0   1.0   2.0
1  3.0   4.0   5.0
2  6.0   7.0   8.0
3  9.0  10.0  11.0

     b    d    e
0 -1.0  0.0  1.0
1 -1.0  0.0  1.0
2 -1.0  0.0  1.0
3 -1.0  0.0  1.0

Function Application and Mapping

In [8]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

frame = pd.DataFrame(np.random.randn(4,3),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame
np.abs(frame)

def f1(x):
    return x.max() - x.min()

frame.apply(f1) #NOTE: This is with respect to the original frame not the positive np.abs(frame)
frame.apply(f1,axis="columns")

def f2(x):
    return pd.Series([x.max(),x.min()],index=["min","max"])

frame.apply(f2)

def my_format(x):
    return f"{x:.2f}"

frame.map(my_format)

frame["e"].map(my_format)

Utah       0.34
Ohio      -0.18
Texas      0.79
Oregon     1.77
Name: e, dtype: str

Sorting and Ranking

In [ ]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

#SORTING

obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

obj.sort_index()

frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
            index=["three", "one"],
            columns=["d", "a", "b", "c"])

frame.sort_index()
frame = frame.sort_index(axis="columns",ascending=True)
frame

frame = frame.reindex(["one","three"])
frame

frame = frame.sort_index(axis="columns",ascending=False)
frame

obj = pd.Series([4, 7, -3, 2])
obj

obj.sort_values()

obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

obj.sort_values(na_position="first")

frame = pd.DataFrame({"b" : [4,7,-3,2],"a":[41,5,5,2]})
frame
frame.sort_values("b")
frame.sort_values #this won't do shit try this

frame.sort_values(["b","a"]) #but it might sort the first column written here it is b


#RANKING

obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

obj.rank(method="first")
obj.rank(method="max")

frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
         "c": [-2, 5, 8, -2.5]})
frame

frame.rank(axis="columns")
frame.rank(axis="index")

Axis Indexes with Duplicate Labels

In [ ]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj
obj.index.is_unique
obj["a"]
obj["c"]

df = pd.DataFrame(np.random.standard_normal((5, 3)),
            index=["a", "a", "b", "b", "c"])
df
df.loc["b"]
df.loc["c"]

Summarizing and Computing Descriptive Statistics

In [ ]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
        [np.nan, np.nan], [0.75, -1.3]],
        index=["a", "b", "c", "d"],
        columns=["one", "two"])
df

df.sum()
df.sum(axis="columns")
df.sum(axis="columns",skipna=False) #here is NA in any row(not all) then the sum would be Na
df.mean(axis='columns') #there should be at least one non-NaN value to get mean
df.idxmax()
df.idxmin()
df.cumsum()
df.describe() #IMPORTANT

obj = pd.Series(["a", "a", "b", "c"] * 4)
obj
obj.describe()

               AAPL     GOOG     MSFT     DELL
2010-01-01  7199789  3872020  1621678  8911374
2010-01-02  7793694  4213511  4869764  1155066
2010-01-03  1103798  7170780  9170731  9827229
2010-01-04  4172314  1389823  4185841  7988286
2010-01-05  6755316  8688132  9896677  3358994
...             ...      ...      ...      ...
2010-04-06  4799390  4022017  7750397  9386893
2010-04-07  5198728  3234970  4981626  3827116
2010-04-08  3741871  7927074  7627355  4369262
2010-04-09  4153375  4445143  7586817  4452616
2010-04-10  8258652  3024996  2183602  7692754

[100 rows x 4 columns]

Corelation and Covariance

In [ ]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

dates = pd.date_range('2010-01-01', periods=100)
tickers = ['AAPL', 'GOOG', 'MSFT', 'DELL']
price = pd.DataFrame(np.random.randn(100, 4).cumsum(axis=0) + 100, index=dates, columns=tickers)
volume = pd.DataFrame(np.random.randint(1_000_000, 10_000_000, size=(100, 4)), index=dates, columns=tickers)
price
volume

#SEE THIS OPERATION AFTER YOU LEARN THESE TYPE OF THINGS COME BACK TO PAAGE 186 OF THE BOOK PYTHON FOR DATA ANALYSIS

Unique Values, Value Counts, and Membership

In [4]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])
uniques = obj.unique()
print(uniques)
print(obj.value_counts())

mask = obj.isin(["b","c"])
mask

print(obj[mask])

to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
unique_vals = pd.Series(["c", "b", "a"])
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

<StringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str
c    3
a    3
b    2
d    1
Name: count, dtype: int64
0    c
5    b
6    b
7    c
8    c
dtype: str

array([0, 2, 1, 1, 0, 2])